name: Selenium Grid Tests

on:
  workflow_dispatch:
  # Uncomment below to enable automatic run on every push to main
  # push:
  #   branches:
  #     - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:

  chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Chrome Tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from chrome-tests chrome-tests
        continue-on-error: true

      - name: Copy Reports from Container
        if: always()
        run: |
          mkdir -p reports/chrome
          docker compose cp chrome-tests:/app/target/surefire-reports ./reports/chrome/surefire-reports || true
          docker compose cp chrome-tests:/app/target/cucumber-html-reports ./reports/chrome/cucumber-html-reports || true
          docker compose cp chrome-tests:/app/target/cucumber-report.html ./reports/chrome/cucumber-report.html || true
          docker compose cp chrome-tests:/app/target/cucumber.json ./reports/chrome/cucumber.json || true

      - name: Debug Reports Folder
        if: always()
        run: |
          echo "Listing reports folder..."
          ls -R reports || true

      - name: Upload Chrome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-reports
          path: reports/
          if-no-files-found: warn

      - name: Stop Containers
        if: always()
        run: docker compose down


  firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Firefox Tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from firefox-tests firefox-tests
        continue-on-error: true

      - name: Copy Reports from Container
        if: always()
        run: |
          mkdir -p reports/firefox
          docker compose cp firefox-tests:/app/target/surefire-reports ./reports/firefox/surefire-reports || true
          docker compose cp firefox-tests:/app/target/cucumber-html-reports ./reports/firefox/cucumber-html-reports || true
          docker compose cp firefox-tests:/app/target/cucumber-report.html ./reports/firefox/cucumber-report.html || true
          docker compose cp firefox-tests:/app/target/cucumber.json ./reports/firefox/cucumber.json || true

      - name: Debug Reports Folder
        if: always()
        run: |
          echo "Listing reports folder..."
          ls -R reports || true

      - name: Upload Firefox Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firefox-reports
          path: reports/
          if-no-files-found: warn

      - name: Stop Containers
        if: always()
        run: docker compose down
