name: Selenium Grid Tests

on:
  workflow_dispatch:
  # Uncomment below to enable automatic run on every push to main
  # push:
  #   branches:
  #     - main

jobs:

  chrome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Reports Directory
        run: |
          mkdir -p reports/chrome/html-reports reports/chrome/surefire-reports
          chmod -R 777 reports

      - name: Run Chrome Tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from chrome-tests chrome-tests

      - name: Fix Report Permissions
        if: always()
        run: sudo chown -R $USER:$USER reports/ || true

      - name: Debug Reports Folder
        if: always()
        run: |
          echo "Listing reports folder..."
          ls -R reports || true

      - name: Upload Chrome Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: chrome-reports
          path: reports/
          if-no-files-found: warn

      - name: Stop Containers
        if: always()
        run: docker compose down


  firefox:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Reports Directory
        run: |
          mkdir -p reports/firefox/html-reports reports/firefox/surefire-reports
          chmod -R 777 reports

      - name: Run Firefox Tests
        run: docker compose up --build --abort-on-container-exit --exit-code-from firefox-tests firefox-tests

      - name: Fix Report Permissions
        if: always()
        run: sudo chown -R $USER:$USER reports/ || true

      - name: Debug Reports Folder
        if: always()
        run: |
          echo "Listing reports folder..."
          ls -R reports || true

      - name: Upload Firefox Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: firefox-reports
          path: reports/
          if-no-files-found: warn

      - name: Stop Containers
        if: always()
        run: docker compose down
